name=input("what's your name? ")
print("hello there, "+name.capitalize())
print("your name is "+str(len(name))+" letters long")
print("the first letter on your name is : "+name[0]+" and the last letter on your name is : "+name[-1])
print(name[1:len(name)-1])
